pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "a3"
include(":core:world-api")
include(":core:world")
include(":core:json")
include(":core:admission")
include(":core:temporal")
include(":core:truth")
include(":core:envelope")
include(":core:confidence")
include(":core:t12")
include(":core:action")
include(":core:runtime")
include(":prediction")
include(":projection")
include(":a3ui")
include(":a3ui:lifecycle")
project(":a3ui:lifecycle").projectDir = file("a3ui/lifecycle")
include(":renderers:android-core")
include(":renderers:android-compose")
include(":renderers:mac-compose")
include(":adapters:mcp")
include(":intent-model")
include(":launcher")
include(":broker")
include(":agent")
include(":showcase")
project(":showcase").projectDir = file("showcase/android")
include(":showcase:mac")
project(":showcase:mac").projectDir = file("showcase/mac")
include(":overlay:common")
include(":overlay:android")
include(":overlay:mac")
include(":conformance")
include(":a3ui:conformance")
project(":a3ui:conformance").projectDir = file("conformance/a3ui")
include(":a3ui:conformance:android")
project(":a3ui:conformance:android").projectDir = file("conformance/a3ui/android")
include(":a3ui:conformance:mac")
project(":a3ui:conformance:mac").projectDir = file("conformance/a3ui/mac")
